"""Cross-platform first-run setup — the no-bash replacement for scripts/setup.sh.

Generates a JWT secret and an admin password hash, then writes backend/.env.
Runs entirely on the Python + bcrypt already inside the backend image, so it works
identically on macOS, Linux, and Windows with no openssl/sed/read/bash.

Usage (Docker — the documented user path):
    docker compose run --rm backend python -m app.setup

Usage (native dev, from backend/):
    uv run python -m app.setup

Non-interactive (CI / scripted): set FIREMASTER_ADMIN_PASSWORD (and optionally
FIREMASTER_ADMIN_USERNAME, FIREMASTER_FORCE_SETUP=1) in the environment.
"""

from __future__ import annotations

import os
import secrets
import sys
from getpass import getpass
from pathlib import Path

import bcrypt

# backend/.env — relative to this file (app/setup.py -> app -> backend), so it does
# not matter what the current working directory is. This is the same file the app
# reads at runtime and the same one scripts/setup.sh wrote.
ENV_PATH = Path(__file__).resolve().parent.parent / ".env"

# Repo-root .env — this is a DIFFERENT file with a different job. docker-compose.yml
# deliberately has no top-level env_file (interpolation mangles the "$" sequences in the
# bcrypt hash and breaks login), so backend/.env is bind-mounted and read directly by
# pydantic. That means values written there never reach the postgres or redis containers.
# Compose reads the repo-root .env for ${VAR} interpolation, so the database and cache
# passwords have to live here or the services come up with the placeholder defaults.
ROOT_ENV_PATH = Path(__file__).resolve().parent.parent.parent / ".env"

# Generated credentials use token_urlsafe (charset A-Za-z0-9-_) rather than a charset with
# punctuation. Compose interpolates the root .env, so a "$" in a password would be eaten or
# would expand to something else entirely.
_PASSWORD_BYTES = 24

ROOT_ENV_TEMPLATE = """\
# Compose interpolation values. Read by docker compose, NOT by the application.
# Generated by app.setup — keep this file out of version control.

# Interface the published ports bind to. 127.0.0.1 keeps the stack reachable from this
# machine only. Set to 0.0.0.0 to expose it to your whole LAN — only do that if you have
# also put real authentication in front of it.
BIND_HOST=127.0.0.1

# Database and cache credentials.
# WARNING: postgres only applies POSTGRES_PASSWORD when it initialises an empty data
# directory. If you change it later against an existing pgdata volume, postgres keeps the
# old password and every connection fails. Either run `docker compose down -v` (destroys
# the database) or change it in-place with ALTER USER.
POSTGRES_USER={pguser}
POSTGRES_PASSWORD={pgpw}
POSTGRES_DB={pgdb}
REDIS_PASSWORD={redispw}

# Images. Default to locally built tags so `docker compose up --build` runs YOUR code,
# including any local security fixes. Point these at a registry to pull instead.
# FIREMASTER_BACKEND_IMAGE=firemaster-backend:local
# FIREMASTER_FRONTEND_IMAGE=firemaster-frontend:local

# Host ports (optional overrides).
# POSTGRES_HOST_PORT=5432
# REDIS_HOST_PORT=6379
# BACKEND_HOST_PORT=8000
# FRONTEND_HOST_PORT=5173
"""

# Template mirrors .env.example. The DB/Redis URLs stay on localhost (correct for the
# native path); the Docker path overrides them to service names via compose, so this
# value is irrelevant inside containers. {jwt} and {pwhash} are filled in below.
ENV_TEMPLATE = """\
# Database
POSTGRES_USER={pguser}
POSTGRES_PASSWORD={pgpw}
POSTGRES_DB={pgdb}
DATABASE_URL=postgresql+asyncpg://{pguser}:{pgpw}@localhost:5432/{pgdb}
DATABASE_URL_SYNC=postgresql://{pguser}:{pgpw}@localhost:5432/{pgdb}

# Redis
REDIS_URL=redis://:{redispw}@localhost:6379/0

# Auth — generated by app.setup. Do not commit real values.
JWT_SECRET_KEY={jwt}
AUTH_USERNAME={username}
AUTH_PASSWORD_HASH={pwhash}

# CORS (comma-separated origins, default localhost dev server)
CORS_ORIGINS=http://localhost:5173

# Monarch Money
MONARCH_SESSION_FILE=.monarch_session

# Anthropic (optional — only needed for in-app AI advisor, not Claude Code)
ANTHROPIC_API_KEY=

# App
APP_ENV=development
# Log every SQL statement to the console (debugging only — very noisy)
DATABASE_ECHO=false
"""


def _interactive() -> bool:
    return sys.stdin is not None and sys.stdin.isatty()


def _resolve_password() -> str:
    """From FIREMASTER_ADMIN_PASSWORD if set, else prompt twice and confirm."""
    env_pw = os.environ.get("FIREMASTER_ADMIN_PASSWORD")
    if env_pw:
        if len(env_pw) < 1:
            sys.exit("ERROR: FIREMASTER_ADMIN_PASSWORD is empty.")
        return env_pw

    if not _interactive():
        sys.exit(
            "ERROR: no TTY and FIREMASTER_ADMIN_PASSWORD is not set.\n"
            "       Run with a terminal (docker compose run allocates one) or set the env var."
        )

    pw = getpass("Choose an admin password: ")
    if not pw:
        sys.exit("ERROR: password cannot be empty.")
    if getpass("Confirm password: ") != pw:
        sys.exit("ERROR: passwords don't match.")
    return pw


def _write_private(path: Path, content: str) -> None:
    """Write with owner-only permissions, created restrictive from the start.

    os.open with mode 0o600 avoids the window where the file exists world-readable between
    creation and a later chmod.
    """
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(content)


def _read_env_values(path: Path) -> dict[str, str]:
    """Minimal KEY=VALUE parse — enough to reuse credentials we previously generated."""
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def _resolve_infra_credentials() -> dict[str, str]:
    """Reuse credentials already in the root .env, generate any that are missing.

    Reuse matters: the root .env feeds the postgres container and backend/.env feeds the
    application. If setup generated a fresh password on every run, re-running it would leave
    the app holding a password the already-initialised database no longer accepts.
    """
    existing = _read_env_values(ROOT_ENV_PATH)
    return {
        "pguser": existing.get("POSTGRES_USER") or "firemaster",
        "pgdb": existing.get("POSTGRES_DB") or "firemaster",
        "pgpw": existing.get("POSTGRES_PASSWORD") or secrets.token_urlsafe(_PASSWORD_BYTES),
        "redispw": existing.get("REDIS_PASSWORD") or secrets.token_urlsafe(_PASSWORD_BYTES),
    }


def _sync_root_env(creds: dict[str, str]) -> str:
    """Create the root .env, or append only the keys it is missing.

    Never rewrites an existing file: it may hold port overrides or a deliberate BIND_HOST
    the user set by hand.
    """
    if not ROOT_ENV_PATH.exists():
        _write_private(ROOT_ENV_PATH, ROOT_ENV_TEMPLATE.format(**creds))
        return "created"

    existing = _read_env_values(ROOT_ENV_PATH)
    required = {
        "POSTGRES_USER": creds["pguser"],
        "POSTGRES_DB": creds["pgdb"],
        "POSTGRES_PASSWORD": creds["pgpw"],
        "REDIS_PASSWORD": creds["redispw"],
    }
    missing = {k: v for k, v in required.items() if k not in existing}
    if not missing:
        return "already complete"

    with ROOT_ENV_PATH.open("a", encoding="utf-8") as fh:
        fh.write("\n# Added by app.setup — required by docker-compose.yml interpolation.\n")
        for key, value in missing.items():
            fh.write(f"{key}={value}\n")
    os.chmod(ROOT_ENV_PATH, 0o600)
    return f"appended {', '.join(missing)}"


def main() -> None:
    force = "--force" in sys.argv or os.environ.get("FIREMASTER_FORCE_SETUP") == "1"

    print("=== FIREMaster Setup ===\n")

    if ENV_PATH.exists() and not force:
        if _interactive():
            reply = input(f"{ENV_PATH} already exists. Overwrite? (y/N) ").strip().lower()
            if reply != "y":
                print("Aborted. Existing .env unchanged.")
                return
        else:
            sys.exit(
                f"ERROR: {ENV_PATH} already exists. Re-run with --force "
                "(or FIREMASTER_FORCE_SETUP=1) to overwrite."
            )

    username = os.environ.get("FIREMASTER_ADMIN_USERNAME", "admin")
    password = _resolve_password()

    jwt_secret = secrets.token_hex(32)
    pwhash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()

    creds = _resolve_infra_credentials()
    reused = ROOT_ENV_PATH.exists() and "POSTGRES_PASSWORD" in _read_env_values(ROOT_ENV_PATH)

    content = ENV_TEMPLATE.format(jwt=jwt_secret, username=username, pwhash=pwhash, **creds)
    # Write with restrictive permissions (owner-only) to protect secrets at rest.
    _write_private(ENV_PATH, content)
    root_status = _sync_root_env(creds)

    print("\n=== Setup complete ===")
    print(f"  App config:   {ENV_PATH}")
    print(f"  Compose vars: {ROOT_ENV_PATH}  ({root_status})")
    print(f"  Username:     {username}")
    print("  JWT key:      (generated, 64 hex chars)")
    print("  Password:     (hashed with bcrypt)")
    print(
        "  DB/Redis:     (reused from existing root .env)"
        if reused
        else "  DB/Redis:     (random passwords generated)"
    )
    print("\nBoth files are chmod 0600 and gitignored. Do not commit them.")
    print(
        "Services bind to 127.0.0.1 by default — reachable from this machine only.\n"
        "Set BIND_HOST in the root .env to change that."
    )
    if reused:
        print(
            "\nNote: an existing database volume keeps the password it was initialised with.\n"
            "      If you ever change POSTGRES_PASSWORD, run `docker compose down -v` (this\n"
            "      destroys the database) or update it in-place with ALTER USER."
        )
    print("\nNext step:  docker compose up --build   (then open http://localhost:5173)")


if __name__ == "__main__":
    main()
