"""Cross-platform first-run setup — the no-bash replacement for scripts/setup.sh.

Generates a JWT secret and an admin password hash, then writes backend/.env.
Runs entirely on the Python + bcrypt already inside the backend image, so it works
identically on macOS, Linux, and Windows with no openssl/sed/read/bash.

Usage (Docker — the documented user path):
    docker compose run --rm backend python -m app.setup

Usage (native dev, from backend/):
    uv run python -m app.setup

Non-interactive (CI / scripted): set FIREMASTER_ADMIN_PASSWORD (and optionally
FIREMASTER_ADMIN_USERNAME, FIREMASTER_FORCE_SETUP=1) in the environment.
"""

from __future__ import annotations

import os
import secrets
import sys
from getpass import getpass
from pathlib import Path

import bcrypt

# backend/.env — relative to this file (app/setup.py -> app -> backend), so it does
# not matter what the current working directory is. This is the same file the app
# reads at runtime and the same one scripts/setup.sh wrote.
ENV_PATH = Path(__file__).resolve().parent.parent / ".env"

# Template mirrors .env.example. The DB/Redis URLs stay on localhost (correct for the
# native path); the Docker path overrides them to service names via compose, so this
# value is irrelevant inside containers. {jwt} and {pwhash} are filled in below.
ENV_TEMPLATE = """\
# Database
POSTGRES_USER=firemaster
POSTGRES_PASSWORD=firemaster
POSTGRES_DB=firemaster
DATABASE_URL=postgresql+asyncpg://firemaster:firemaster@localhost:5432/firemaster
DATABASE_URL_SYNC=postgresql://firemaster:firemaster@localhost:5432/firemaster

# Redis
REDIS_URL=redis://localhost:6379/0

# Auth — generated by app.setup. Do not commit real values.
JWT_SECRET_KEY={jwt}
AUTH_USERNAME={username}
AUTH_PASSWORD_HASH={pwhash}

# CORS (comma-separated origins, default localhost dev server)
CORS_ORIGINS=http://localhost:5173

# Monarch Money
MONARCH_SESSION_FILE=.monarch_session

# Anthropic (optional — only needed for in-app AI advisor, not Claude Code)
ANTHROPIC_API_KEY=

# App
APP_ENV=development
# Log every SQL statement to the console (debugging only — very noisy)
DATABASE_ECHO=false
"""


def _interactive() -> bool:
    return sys.stdin is not None and sys.stdin.isatty()


def _resolve_password() -> str:
    """From FIREMASTER_ADMIN_PASSWORD if set, else prompt twice and confirm."""
    env_pw = os.environ.get("FIREMASTER_ADMIN_PASSWORD")
    if env_pw:
        if len(env_pw) < 1:
            sys.exit("ERROR: FIREMASTER_ADMIN_PASSWORD is empty.")
        return env_pw

    if not _interactive():
        sys.exit(
            "ERROR: no TTY and FIREMASTER_ADMIN_PASSWORD is not set.\n"
            "       Run with a terminal (docker compose run allocates one) or set the env var."
        )

    pw = getpass("Choose an admin password: ")
    if not pw:
        sys.exit("ERROR: password cannot be empty.")
    if getpass("Confirm password: ") != pw:
        sys.exit("ERROR: passwords don't match.")
    return pw


def main() -> None:
    force = "--force" in sys.argv or os.environ.get("FIREMASTER_FORCE_SETUP") == "1"

    print("=== FIREMaster Setup ===\n")

    if ENV_PATH.exists() and not force:
        if _interactive():
            reply = input(f"{ENV_PATH} already exists. Overwrite? (y/N) ").strip().lower()
            if reply != "y":
                print("Aborted. Existing .env unchanged.")
                return
        else:
            sys.exit(
                f"ERROR: {ENV_PATH} already exists. Re-run with --force "
                "(or FIREMASTER_FORCE_SETUP=1) to overwrite."
            )

    username = os.environ.get("FIREMASTER_ADMIN_USERNAME", "admin")
    password = _resolve_password()

    jwt_secret = secrets.token_hex(32)
    pwhash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()

    content = ENV_TEMPLATE.format(jwt=jwt_secret, username=username, pwhash=pwhash)
    # Write with restrictive permissions (owner-only) to protect secrets at rest.
    fd = os.open(ENV_PATH, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(content)

    print("\n=== Setup complete ===")
    print(f"  File:     {ENV_PATH}")
    print(f"  Username: {username}")
    print("  JWT key:  (generated, 64 hex chars)")
    print("  Password: (hashed with bcrypt)\n")
    print("Next step:  docker compose up   (then open http://localhost:5173)")


if __name__ == "__main__":
    main()
